name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80d9763ad4ceede04a1cceff31fea71c9217d888876951ee81a1778f276b2414"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
