name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d4c99d3e9aaf44810c59d12e563d7fbbef9775fc5be14d35dbe0fc5abdb8714"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
