name = "THE_ONE"
author = "j"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7887ac18eb1512afb2e27791b8a7f2c489fd4a6c0c7e3314edba6da7e2268539"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
