name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81e54384df835ec14511cc1d124731ea1bfe1685ef0b0f036fce910ffe5df535"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
