name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a162d909cc10f71e0b645383be42b5d9b6c5f5ce66e5a03e58bce033c01717b6"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
