name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a927702053a37d4e69cf427d44acf2553360e26e20fbe145c57fdd51d47e710"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
