name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65a2559d114cd40a0ba9f6dcfd78bc9e42c57cd72b2de074b12c08cee931fa74"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
