name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45f42f03d8835359598a211e771c270bd49b0791e5f6e8ea1e94ff71173fd7c3"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
