name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77f5e6bca56ce8f07c6505a48ca4caf1e210afef8bd0515614f31369c4badf71"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
