name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd1098bfb533418d8340a4c79111f6db253821ca298ccfdf5cdf4ab7776d87e6"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
