name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a46528258d8855383456e091edc8e42d166be9ade6ff480cdc896a87985399d6"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
