name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9572bb095be392431ff48be81407cdc19a2bee6220b644f9ff091def2c87674"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
