name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "832e386a19e1b0a2cdde9333e5353af03de9eb7d7fcbad322f31ed1894075163"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
