name = "THE_ONE"
author = "j"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11e7390e8c32fedbf7db11b67db0c2ac53e2e8c15d1c96332f09d09c90c76c83"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
