name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "641319a683b0f75543fa32e6ec9fbd02cf977fc99b57d4ebb30c4447777010de"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
