name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93d0bc131621062dbb14212fb42a8114d6942723fba5a09da5c61441ece79643"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
