name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "498661817604013abd4e7b508d3d1fce37087cb7414ef30a3dcfc077815d1577"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
