name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c29873427f59faead5e4c156061f9f67e0897551017f346c494d3d7981790d85"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
