name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90fccf3874d2b790d05f1d56a3519c710f186a9d1bd1c50b7da62fad3cbd3dde"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
