name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9b954f16f877b9d062a8b1fc322ac76da44741d8aed2b1f67bb61585bc9219a"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
