name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b02ad247fcd41d70f5cd8f48b4de99714a98a1f0f0b90df8ba9bbd848a691889"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
