name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8d3bcdaf425c61507008d603e09d60b633285e904d9f627a97a676964f70867"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
