name = "THE_ONE"
author = "j"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29747186799aec051d45aa9eabe4b9053f9d7584b8f3a2fdb1a1ccf0c8c921c5"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
