name = "THE_ONE"
author = "j"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be8df1b1ae35f020791f944ca4c7f2bc515c5bd2cf3fec1cbcdb387358b13d3e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
