name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "944019e9d63f7e9cb3427f5da5d926e8a0338f2c067bd031098eae806e7e025c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
