name = "THE_ONE"
author = "j"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8192d36d6ff03c8aab0973242b03605c83b60f7ae3323e646a21b56dd404740e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
