name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4f7f36962854e52b5a4020fbabf15f7aa9bca270097446dd159a4bbc840d19f"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
