name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b724e7c9899e876592cee99deaa5727ae8f6f3a590e711d8c73a3b7db7086ae1"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
