name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1200991bef38825a31098f154f3c0295606b220c3ee0c7f420521f842ff26d60"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
