name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9439cec834ad307b632954a6dd8941315ad6022212dc6dcc796298711f8dba86"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
