name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "736ee83b37067fc856104ac002b153385eb5f532d8db9549962654bfa965e464"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
