name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad147eaef592380bb3c209352997468cb5df002f13af1729139a5d869c2e315f"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
