name = "THE_ONE"
author = "j"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46bd236d701c68e2297c39d4a20456878fe750b2abc965318c4eff4bcdbe4761"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
