name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e654f1b4f992ff2eb78fd19f26ae5d3eb8651b623ac07295aa262a80b1e26672"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
