name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d02577cfc5754c2daee0e40e8eeb0876273802bca68a7dda0a13f57f80d5cc56"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
