name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad2d0614a3af44c3b4f87886d3ebd1a8ad5d8cf889931468d455c388fe848768"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
