name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7039210d5f92005e76ad4f886228c3f936683a1c05c2a770dd65d685e8b8ad25"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
