name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "946d95f2ffd80ea414e7dceae25452a0d12fb3d690e6b5fc9b85c31f4695a0fe"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
