name = "The One Modpack"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ac1923b36572852e2f46ed314dde3e744b29e7ed2a32c5721f401ff563d7b99"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
