
["Configs for MHC Mod"]

	["Configs for MHC Mod"."Kosei Settings"]
		#Memorized all techniques from the beginning (default = false) 
		Kosei = false

	["Configs for MHC Mod"."Monster Settings"]
		#Can Monsters spawn in Minecraft? (default = true) 
		Monster = true
		#Can Villan spawn in Minecraft? (default = true) 
		Villan = true
		#Can Hero spawn in Minecraft? (default = true) 
		Hero = true

	["Configs for MHC Mod"."Exp Settings"]

		["Configs for MHC Mod"."Exp Settings"."Multiplier of experience points received when exorcising cursed spirits"]

			["Configs for MHC Mod"."Exp Settings"."Multiplier of experience points received when exorcising cursed spirits"." (default = 1"]
				"0) " = 1.0

